routes/web.php
<?php

use App\Http\Controllers\Backend\ChangePassword;
use App\Http\Controllers\Backend\ChangePasswordController;
use App\Http\Controllers\Backend\CityController;
use App\Http\Controllers\Backend\CountryController;
use App\Http\Controllers\Backend\DepartmentController;
use App\Http\Controllers\Backend\StateController;
use App\Http\Controllers\Backend\ReportsController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\AdminHomeController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Backend\UnitRankController;
use App\Http\Controllers\Backend\UnitController;
use App\Http\Controllers\Backend\FinancialYearController;
use App\Http\Controllers\Backend\IndicatorGroupController;
use App\Http\Controllers\Backend\IndicatorController;
use App\Http\Controllers\Backend\TemplatesController;
use App\Http\Controllers\Backend\IndicatorCategoryController;
use App\Http\Controllers\Backend\TemplateIndicatorsController;
use App\Http\Controllers\Backend\TemplateIndicatorGroupController;
use App\Http\Controllers\Backend\MasterIndicatorController;
use App\Http\Controllers\Backend\PmmuController;
use App\Http\Controllers\Auth\LoginController;




use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [LoginController::class, 'showLoginForm'])->name('login');



Auth::routes();

Route::middleware(['auth', 'role:admin'])->group(function () {

    Route::resource('template-groups',TemplateIndicatorGroupController::class);
    Route::resource('template-indicators',TemplateIndicatorsController::class);
    Route::get('admin-dashboard', [AdminHomeController::class, 'index'])->name('admin-dashboard');
    Route::get('templates', [TemplatesController::class, 'index'])->name('templates');
    Route::resource('unit-ranks.fy',TemplatesController::class);
    Route::resource('unit-ranks.fy.template-groups',TemplateIndicatorGroupController::class);
    Route::resource('unit-ranks.fy.template-groups.template-indicators',TemplateIndicatorsController::class);
    Route::resource('master-indicator',MasterIndicatorController::class);
    Route::resource('unit-ranks.master-indicator',MasterIndicatorController::class);

});


Route::middleware(['auth', 'role:user'])->group(function () {

    Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('reports', [ReportsController::class, 'index'])->name('reports');
    Route::get('reports/excel_reports', [ReportsController::class, 'excel_reports'])->name('excel_reports');
    Route::get('file-export', [ReportsController::class, 'fileExport'])->name('file-export');
    Route::get('reports/test_reports', [ReportsController::class, 'test_report'])->name('test_report');
    Route::resource('users', UserController::class);
    Route::resource('indicators', IndicatorController::class);
    Route::resource('unit-ranks', UnitRankController::class);
    Route::resource('unit', UnitController::class);
    Route::resource('fy', FinancialYearController::class);
    Route::resource('indicator-groups', IndicatorGroupController::class);
    Route::resource('unit-ranks.units',UnitController::class);
    //Route::resource('unit-ranks.units.fy',UnitController::class);
    Route::resource('unit-ranks.units.fy', FinancialYearController::class)->shallow();
    Route::get('unit-ranks/{unit_rank}/fy/{fy}/unit_excel',[ReportsController::class,"unit_excel"])->name('unit_excel');
    //Route::resource('unit-ranks.units.fy.indicator-groups', IndicatorGroupController::class);
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/simple_pmmu',[IndicatorController::class,"createSimplePmmuPDF"])->name('simple_pmmu');
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/complex_pmmu',[IndicatorController::class,"createComplexPmmuPDF"])->name('complex_pmmu');
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/pmmu',[IndicatorController::class,"preview"])->name('pmmu');
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/pdf',[IndicatorController::class,"createPDF"])->name('pdf');
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/download_template',[IndicatorController::class,"download_template"])->name('download_template');
    Route::get('unit-ranks/{unit_rank}/units/{unit}/fy/{fy}/indicator-groups/update_targets',[IndicatorController::class,"update_targets"])->name('update_targets');
    Route::resource('unit-ranks.units.fy.indicator-groups',IndicatorController::class);
    Route::resource('unit-ranks.units.fy.indicator-groups.indicators',PmmuController::class);
    Route::post('users/{user}/change-password', [ChangePasswordController::class, 'change_password'])->name('users.change.password');
    Route::get('users/{user}/change-password', [ChangePasswordController::class, 'change_password_form'])->name('user_change_password_form');
    Route::get('users/{user}/permissions', [UserController::class, 'permissions_form'])->name('user.permissions');


  

});

app/Models/TemplateIndicatorGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TemplateIndicatorGroup extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'unit_rank_id',
        'financial_year_id',
        'description',
        'order'
    ];

    public function template_indicators( )
    {

    
        return $this->hasMany(TemplateIndicator::class,'indicator_group_id');
      
    }


    public function fy()
    {
        return $this->belongsTo(FinancialYear::class,'financial_year_id');
    }

   
}

app/Http/Controllers/Backend/TemplateIndicatorGroupController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Requests\StoreTemplateIndicatorGroupRequest;
use App\Http\Requests\UpdateTemplateIndicatorGroupRequest;
use App\Http\Controllers\Controller;
use App\Models\TemplateIndicatorGroup;
use App\Models\UnitRank;
use App\Models\Unit;
use App\Models\FinancialYear;

use Illuminate\Http\Request;

class TemplateIndicatorGroupController extends Controller
{
    public function index(Request $request ,UnitRank $unit_rank,FinancialYear $fy)

    {
        $templateindicatorgroups = TemplateIndicatorGroup::where('unit_rank_id',$unit_rank->id)
        ->where('financial_year_id',$fy->id)
        ->get();

        

        if ($request->has('search')) {
            $templateindicatorgroups= TemplateIndicatorGroup::where('unit_rank_id',$unit_rank->id)
                    ->where('financial_year_id',$fy->id)
                    ->where('name', 'like', "%{$request->search}%")
                    ->get();
        }


        return view('admin.template_indicator_groups.index',compact('templateindicatorgroups','unit_rank','fy'));
    }



    



    public function create(Request $request ,UnitRank $unit_rank,FinancialYear $fy){

     
      

        return view('admin.template_indicator_groups.create',compact('unit_rank','fy'));

    }

    public function store(UnitRank $unit_rank ,FinancialYear $fy,Request $request ){
        

        TemplateIndicatorGroup::create([

            'name' =>               $request->name,
            'description' =>        $request->description,
            'order' =>              $request->order,
            'unit_rank_id' =>       $unit_rank->id,
            'financial_year_id' =>  $fy->id,
        ]);

        return redirect()->route('unit-ranks.fy.template-groups.index',[$unit_rank->id ,$fy->id])->with('message', 'Template Group Register Succesfully');




    }

    public function edit(UnitRank $unit_rank,FinancialYear $fy,TemplateIndicatorGroup $template_group){

      
        return view('admin.template_indicator_groups.edit',compact('unit_rank','fy','template_group'));
    }

    public function update(UnitRank $unit_rank,FinancialYear $fy,TemplateIndicatorGroup $template_group,Request $request){


        $template_group->update([

            'name' =>               $request->name,
            'description' =>        $request->description,
            'order' =>              $request->order,
        
        
        ]);

        return redirect()->route('unit-ranks.fy.template-groups.index',[$unit_rank->id, $fy->id])->with('message', 'Group Updated Successfully');

    }

}

resources/views/admin/template_indicator_groups/create.blade.php
@extends('layouts.main')

@section('content')

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $unit_rank->name }} - FY {{ $fy->name  }} </h1>
    </div>

   
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        {{ __('Create New Group') }}
                        <a href="{{ route('unit-ranks.fy.template-groups.index',[$unit_rank->id,$fy->id]) }}" class="float-right">Back</a>
                    </div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('unit-ranks.fy.template-groups.store',[$unit_rank->id,$fy->id]) }}">
                            @csrf

                        

                            <div class="form-group row">
                                <label for="name"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Indicator Name') }}</label>

                                <div class="col-md-12">
                                    <input id="name" type="text"
                                        class="form-control @error('name') is-invalid @enderror" name="name"
                                        value="{{ old('name') }}" required autocomplete="username" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="description"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                                <div class="col-md-12">
                                    <input id="description" type="text" 
                                        class="form-control @error('description') is-invalid @enderror" name="description" rows="3"
                                        value="{{ old('description') }}" required autocomplete="description" autofocus>

                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="order"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Order') }}</label>

                                <div class="col-md-6">
                                    <input id="order" type="number" 
                                        class="form-control @error('order') is-invalid @enderror" name="order"
                                        value="{{ old('order') }}" required autocomplete="order" autofocus>

                                    @error('order')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                           

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create New Group') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/template_indicator_groups/edit.blade.php
@extends('layouts.main')

@section('content')

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $unit_rank->name }} - FY {{ $fy->name  }} </h1>
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Group </h1>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        {{ __('Edit Group') }}
                        <a href="{{ route('unit-ranks.fy.template-groups.index', [$unit_rank->id  ,$fy->id]) }}" class="float-right">Back</a>
                    </div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('unit-ranks.fy.template-groups.update',  [$unit_rank->id , $fy->id,$template_group->id]) }}">
                            @csrf
                            @method('PUT')



                            <div class="form-group row">
                                <label for="name"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-12">
                                    <input id="name" type="text"
                                        class="form-control @error('name') is-invalid @enderror" name="name"
                                        value="{{ old('name', $template_group->name) }}" required>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="description"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Group Description') }}</label>

                                <div class="col-md-12">
                                    <input id="description" type="text"
                                        class="form-control @error('description') is-invalid @enderror" name="description"
                                        value="{{ old('description', $template_group->description) }}" required>

                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>



                            <div class="form-group row">
                                <label for="order"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Group Order') }}</label>

                                <div class="col-md-12">
                                    <input id="order" type="number"
                                        class="form-control @error('order') is-invalid @enderror" name="order"
                                        value="{{ old('order', $template_group->order) }}" required>

                                    @error('order')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>



                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update Group') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="m-2 p-2">
                    <form method="POST" action="{{ route('unit-ranks.fy.template-groups.destroy',  [$unit_rank->id , $fy->id , $template_group->id]) }}">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger">Disable {{ $template_group->name }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/template_indicator_groups/index.blade.php
@extends('layouts.main')

@section('content')

    <!-- Page Heading -->
    <div class="card">
        <div class="card-body">
    
    <div class="d-flex justify-content-center .mb-15" >
        <div class="row ">
            <h1 class="h3 mb-0 text-gray-800">{{ $unit_rank->name }} {{ $fy->name }} Template</h1>
        </div>
       
    </div>
        
</div>
</div>

<div class="card">
    <div class="card-body">
    <div class="row">
        <div class="card  mx-auto">
            <div>
                @if (session()->has('message'))
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                @endif
            </div>
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <form method="GET" action="{{ route('unit-ranks.fy.show',[$unit_rank->id,$fy->id ]) }}">
                            <div class="form-row align-items-center">
                                <div class="col">
                                    <input type="search" name="search" class="form-control mb-2" id="inlineFormInput"
                                        placeholder="Search Indicator Group">
                                </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-primary mb-2">Search</button>
                                </div>

                                <div class="col">
                                    <a href="{{ route('unit-ranks.fy.template-groups.index', [$unit_rank->id,$fy->id]) }}" class="btn btn-success">Preview PMMU Template </a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div>
                        <a href="{{ route('unit-ranks.fy.template-groups.create',[$unit_rank->id,$fy->id ]) }}" class="btn btn-primary mb-2">Create New Group </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered" >
                    <thead>
                        <tr>
                            <th scope="col"># </th>
                            <th scope="col"> Indicator Group Name</th>
                            <th scope="col"> Description</th>
                            <th scope="col"> Weight</th>
                            <th scope="col"> Edit</th>
                            <th scope="col"> Indicators</th>
                
                
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($templateindicatorgroups as $group)
                            <tr>
                                <th> <b>{{ $group->order }} </b></th>
                                <th> {{ $group->name }} </th> 
                                <th> <b>{{ substr($group->description,0,10)}} </b></th> 
                                <th> <b> {{ $group->template_indicators->sum('indicator_weight')}}</b></th> 
                                <th> <a href="{{ route('unit-ranks.fy.template-groups.edit', [$unit_rank->id,$fy->id , $group->id]) }}"> Edit</a>   </th>
                                <th> <a href="{{ route('unit-ranks.fy.template-groups.template-indicators.index', [$unit_rank->id,$fy->id,$group->id]) }}", class="btn btn-success" >Template Indicators <span class="badge bg-secondary">{{ $group->template_indicators->count() }}</span> </th>
                            </tr>
                            @endforeach
                    </tbody>  
                    
                    <tfoot>
                        <tr>
                            <td class="right font-weight-bold" colspan="3">Grand Total: </td>
                            <td class="right"> </td>
                            {{-- <td class="right">{{ $group->indicators->sum('indicator_weight')}}</span></td> --}}
                        </tr>
                    </tfoot>
                    
                </table>
            </div>
        </div>

    </div>

</div>
</div>

  
@endsection